name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Minify EPUBs
        shell: pwsh
        run: |
          npm i html-minifier -g
          . .\book-module.ps1 
          Minify .\ostrovityanov-politeconomia\

      - name: Compress EPUBs
        shell: pwsh
        run: |
          . .\book-module.ps1 
          New-Epub .\ostrovityanov-politeconomia\
         
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ostrovityanov-politeconomia
          path: ostrovityanov-politeconomia.epub
