name: CI

on:
  push:
    branches: [ master ]
    tags: 'v*.*.*'
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  compress:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        
      - name: Setup tooling
        run: sudo npm i html-minifier -g

      - name: Minify EPUBs
        shell: pwsh
        run: |
          . .\books-module.ps1 
          Minify .\ostrovityanov-politeconomia\

      - name: Compress EPUBs
        shell: pwsh
        run: |
          . .\books-module.ps1 
          New-Epub .\ostrovityanov-politeconomia\
         
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: books
          path: ostrovityanov-politeconomia.epub

  upload:
    needs: compress
    runs-on: ubuntu-latest
    if: contains('refs/heads/master', github.ref)
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: books

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: books
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      
